jenkins:
  systemMessage: "🚀 Welcome to DevOps Course Jenkins Server (Pre-configured by Reza Naipospos)"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "DevOps Administrator"
          password: "${JENKINS_ADMIN_PASSWORD:-admin123}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  globalNodeProperties:
    - envVars:
        env:
          - key: "COURSE_ENV"
            value: "local-machine"

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@devops-course.local"
